notifications:
  email: false
  slack: wtsi-cgpit:ptUMR1tkNyZJYd9TpGoss8WR
env:
  - CC=gcc
addons:
  apt:
    packages:
     - autoconf
     - build-essential
     - curl
     - exonerate
     - libncurses5-dev
     - libpstreams-dev
     - libcurl4-openssl-dev
     - zlib1g-dev
     - libgd-dev
     - libdb-dev

language: perl

perl:
  - "5.16"

install: true

script:
  - ./setup.sh $HOME/vafCorrect-opt 2

