notifications:
  email: false
  slack: wtsi-cgpit:ptUMR1tkNyZJYd9TpGoss8WR

sudo: false

services:
  - docker

script:
 - set -e
 - echo 'Build and check docker image'
 - docker build -t vafcorrect .
 - docker images | grep -c vafcorrect
 - docker run -t --rm vafcorrect cgpVaf.pl -version
