notifications:
  email: false
  slack: wtsi-cgpit:ptUMR1tkNyZJYd9TpGoss8WR
# safelist
#branches:
#  only:
#  - master
env:
  - CC=gcc
addons:
  apt:
    packages:
     - autoconf
     - build-essential
     - curl
     - exonerate 
     - libncurses5-dev
     - libpstreams-dev
     - libcurl4-openssl-dev
     - zlib1g-dev

language: perl

perl:
  - "5.16"

install: true

script:
	- while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
  - ./setup.sh $HOME/vafCorrect-opt

